### PR TITLE
Created helpers to sign user id and email

### PR DESCRIPTION
**Pull request by Larinel**
Hi there!

Just added some simple helpers to sign user id and email according to https://documentation.onesignal.com/docs/identity-verification.

### CODE REVIEW

**Comment by Larinel** [comment]
@zeyneloz Hi!

Could you please review this PR? If it's convenient for you.

**Comment by A-Tokyo** [comment]
Great work @Larinel ✨

**Comment by zeyneloz** [comment]
Thanks for the CR. Looks good to me. Merging.

**Review by zeyneloz — APPROVED** [review]

**Comment by daveslutzkin** [comment]
Any plans to release this change to npm? Would be handy for us.

**Comment by daveslutzkin** [comment]
@zeyneloz can you release this? Or would you like me to help by releasing it for you?

**Pull request merged**
